# 
# ___  ___ ____ _    ____ ___  ___  _   _
#  |  |    |___ |    |  | |__] |__]  \_/   
# _|_ |___ |___ |___ |__| |__] |__]   |    by zBlubba
# (symbols copyed from AdvancedLobby)
#

#  Supported variables:
#  {prefix} - prefix; {user} - username;
#  {maxplayers} - slots of server; {onlineplayers} - online players;
#  more might come in newer versions.
#  not every variable works in every case, just try it!
#  for the scoreboard, you must use other color-codes for the spacers
#  You can find a full guide on https://zblubba.de or on the spigot page :D
# 


lobby_worlds:
  - world
  - lobby

default_gamemode: SURVIVAL
unlimited_food: true
no_damage: true
stop_pickup_items: true
heal_on_join: true

# weather: supported types: CLEAR, RAIN, THUNDER
default_weather: CLEAR
lock_weather: true

# when locked_time equals false and same_as_real true, the plugin takes the time in your real world
# for example: at 8 p.m. the sun is going down and at 3 a.m. it's night.
time:
  locked_time: false
  time: 6000
  same_as_real: true

no_explosions: true
#in vanilla, leaves without a stam nearby despawn
stop_despawning_leaves: true
build_only_lobby_world: true

blocked_commands:
  - /icanhasbukkit
  - /plugins
  - /pl
  - /?
  - /about
  - /ver
  - /version

warp:
  play_sound: true
  sound: ENTITY_EXPERIENCE_ORB_PICKUP

# when a user falls into the void, he would fall forever
# to stop this, you set the y height when the player gets teleported
# this checks only every 1 second due to performance
void:
  teleport_on_fall: true
  yborder: 0
  warp_to_teleport: 'Spawn'

world_change:
  change_gamemode: true
  gamemode: SURVIVAL
  clear_hotbar: true

spawn: 
  enabled: true
  spawn_warp_name: 'Spawn'

join:
  enabled: true
  teleport_on_join: true
  playsound: true
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  send_welcome_message: true

quit:
  enabled: true

launchpads:
  # only oak and stone pressure plates work as launchpad
  enabled: true
  block: REDSTONE_BLOCK
  # general boost
  multiply: 1.5
  # boost in the air
  ymultiply: 1
  effect: true
  sound: true

scoreboard:
  enabled: true
  title: '      &bIce&9Lobby'
  # there is a maximum of 15 lines in the scoreboard
  scores:
    - '&b'
    - '&3➥ &7Your Name'
    - '  &8● &9{user}'
    - '&a'
    - '&3➥ &7Coded by'
    - '  &8● &bzBlubba'
    - '&c'
    - '&3➥ &7visit my Website'
    - '  &8● &9https://zBlubba.de'
    - '&d'
    - '&3➥ &7set your'
    - '  &8● &btext here'
    - '&e'
    - '&f'
    - '       &BYour&9Server'
