name: IceLobby
version: 1.0-ALPHA
main: de.zblubba.icelobby.IceLobby
api-version: 1.19
authors: [ zBlubba ]
description: IceLobby Plugin
website: https://zblubba.de

commands:
  fly:
    description: Allows players to toggle fly
  clearchat:
    description: cleart the chat
    aliases:
      - cc
  spawn:
    description: teleports a player to the spawn
    aliases:
      - l
      - hub
      - lobby
  teleportall:
    description: teleports every player to you
    aliases:
      - tpall
  globalmute:
    description: mutes every player without permission
    aliases:
      - gmute
  help:
    description: helps you to get a better overview
  navigator:
    description: opens the navigator gui
  warp:
    description: warp system for teleporting
  nothing:
    description: nothing
  build:
    description: allows a user to build in the lobby
    aliases:
      - b
  visibility:
    description: changes the visibility of the players
  icelobby:
    description: reloading the plugin
    aliases:
      - il
  coins:
    description: economysystem for the shop
  shop:
    description: opens the shop gui